### ISSUE TITLE
Cannot use pacaur plug-in with ./install

### ISSUE THREAD

**Issue by OxSon** [ajlende/dotbot-pacaur#6]
In order to get the pacaur plugin to work, I have to run, from my dotfiles repo, `dotbot/bin/dotbot -p dotbot-pacaur/pacaur.py -c packages.conf.yaml` rather than `./install -p dotbot-pacaur/pacaur.py -c packages.conf.yaml`. What am I doing wrong?

The output I get is the same as if `./install` was running my default config, then this on `stderr`:

```bash
usage: dotbot [-h] [-Q] [-q] [-v] [-d BASEDIR] [-c CONFIGFILE] [-p PLUGIN]
              [--disable-built-in-plugins] [--plugin-dir PLUGIN_DIR]
              [--no-color] [--version]
dotbot: error: argument -c/--config-file: expected one argument
```

**Comment by ajlende** [comment]
The `./install` command is a thin wrapper on `dotbot/bin/dotbot` iirc and comes from dotbot, so I'm surprised to see that one works and the other doesn't. 

I don't have access to my computer right now because I'm traveling, but I might be able to help with a little more information. 

Does it work when added directly to your `install.conf.yaml`? 

What version of dotbot are you using?

What shell are you using?

And does `./install` not work with other plug-ins or just this one?

**Comment by OxSon** [comment]
Yes it is surprising to me to. I have yet to be able to figure out if it's something I'm doing wrong, or some idiosyncrasy with my system set up, or what exactly is happening.

I will try adding it directly and report back. I haven't tried this approach yet.

`dotbot --version` gives `Dotbot version 1.15.0 (yaml: 3.12)`.

I'm using `zsh`.

`./install` does not work with this plug-in, nor with [dotbot-yaourt](https://github.com/niklas-heer/dotbot-yaourt) nor with [dotbot-yay](https://github.com/oxson/dotbot-yay) (dotbot-yay is functionally the exact same as the yaourt plug-in, I made it by essentially just running `:%s/yaourt/yay` on `dotbot-yaourt`.

**Comment by ajlende** [comment]
What does your `install` script look like? After reading the error again, it looks like you might have missed throwing double quotes around a variable or something.

**Comment by OxSon** [comment]
[this one?](https://github.com/OxSon/.dotfiles/blob/master/install)

**Comment by ajlende** [comment]
Yep, that's where your problem is. It looks like the default `install` script that ships with dotbot doesn't pass through arguments anymore. You can take a look at [my `install` script](https://github.com/ajlende/dotfiles/blob/master/install) to see how I do it. All my configuration files are concatenated and the dotbot command is only run once. The additional arguments that you are having trouble with are passed through with `${@}` at the end of mine.

You can either do what I am doing or hardcode each plugin in your `install` script. I'll update the Readme here with an updated example when I get back to my computer.

**Comment by OxSon** [comment]
Awesome. Thanks for your work! I will mess with mine and when I get it working maybe post an issue on the main dotbot repository.
